server:
  port: 8080
logging:
  level:
    root: INFO
spring:
  application:
    name: demo-mysql

  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/library_db
    username: root
    password: 5382
    driver-class-name: com.mysql.cj.jdbc.Driver

# JPA配置
# spring.jpa.hibernate.ddl-auto=update # 自动更新表结构（开发阶段用，生产环境建议用 validate 或 none）
# spring.jpa.show-sql=true # 打印 SQL 日志（调试用）
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# spring.jpa.properties.hibernate.format_sql=true # 格式化 SQL 语句

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update # 自动更新表结构（开发阶段用，生产环境建议用 validate 或 none）
    show-sql: true # 打印 SQL 日志（调试用）
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true # 格式化 SQL 语句